// Real project list provided by the client (source: internal spreadsheet).
// `company` names are normalized to their canonical form (e.g. "HRS" / "HRS
// Real Estate" -> "HRS Real Estate SA") so the same logo/badge is used
// consistently across rows referring to the same company.
//
// `href` is left undefined for now — individual project detail pages will
// be wired up once the client's admin panel/CMS is in place.
export type Project = {
    name: string;
    company: string | null;
};

export const CURRENT_PROJECTS: Project[] = [
    { name: 'Cugy PP', company: 'Integra SA' },
    { name: 'Greenparc', company: 'Induni & Cie SA' },
    { name: 'Nido', company: 'ALPENDA' },
    { name: 'BIT Pavillon', company: 'ALPENDA' },
    { name: 'Central Malley', company: 'Implenia Suisse SA' },
    { name: 'Passage Morillon', company: 'Implenia Suisse SA' },
    { name: 'Tilia Tower', company: 'HRS Real Estate SA' },
    { name: 'Bougyval', company: 'Frame Entreprise Générale' },
    { name: 'Crèche Plaine-Loup', company: 'TASQ Sàrl' },
    { name: 'Les Terrasses du Lac', company: 'Losinger Marazzi SA' },
    { name: 'Rubans', company: 'Complex Bau AG' },
    { name: 'En Gruvatiez ST2', company: 'ALPENDA' },
    { name: 'Gare-Casino', company: 'HRS Real Estate SA' },
    { name: 'Bergières 42', company: 'Complex Bau AG' },
    { name: 'TRavis', company: 'ALPENDA' },
    { name: 'Tulux', company: 'ISG Schweiz AG' },
    { name: 'HIFI', company: 'Bat-Mann Constructeur' },
    { name: 'Quai Vernet', company: 'Losinger Marazzi SA' },
    { name: 'BMW', company: 'BEG SA' },
    { name: 'Sauges', company: 'Swissroc' },
    { name: 'INARA', company: 'Frame Entreprise Générale' },
    { name: 'Migros Estavayer', company: 'OCS' },
    { name: 'GYBUS', company: 'Implenia Suisse SA' },
    { name: 'Glasson', company: 'Swissroc' },
    { name: 'Nova Vita', company: 'Labac Architecture' },
    { name: 'Gare 25-27', company: 'Bernard Nicod' },
    { name: 'GOLF', company: 'Villvert SA' },
    { name: 'Chanel 37', company: 'Bat-Mann Constructeur' },
    { name: 'Sur le Crêt', company: 'HRS Real Estate SA' }
];

export const COMPLETED_PROJECTS: Project[] = [
    { name: 'Petit Lancy', company: 'Bâtie' },
    { name: 'HRS Real Estate', company: 'HRS Real Estate SA' },
    { name: 'Cully Gare', company: 'Implenia Suisse SA' },
    { name: 'Vertigo', company: 'ALPENDA' },
    { name: 'Rue de Beaumont', company: 'Implenia Suisse SA' },
    { name: 'Floréal 4', company: 'Swissroc' },
    { name: 'Arbora', company: 'Losinger Marazzi SA' },
    { name: 'Eolia', company: 'ALPENDA' },
    { name: 'Rive Droite Orbe', company: 'CSC' },
    { name: 'Osiris', company: 'ALPENDA' },
    { name: 'Côté Gare', company: 'HRS Real Estate SA' },
    { name: 'Chêne 17-19', company: 'ALPENDA' },
    { name: 'Plaine du Loup', company: 'Losinger Marazzi SA' },
    { name: 'Le Day', company: 'ALPENDA' },
    { name: 'Mont de Lavaux', company: 'BEG SA' },
    { name: 'Parcelle', company: 'Salchegger Sàrl' },
    { name: 'Evionnaz Maison Nature Eco', company: 'Sàrl' },
    { name: 'Grand Montfleury', company: 'ALPENDA' },
    { name: 'Bernex', company: 'Implenia Suisse SA' },
    { name: 'Boutique Ferronato', company: null },
    { name: 'Neyruz', company: 'Implenia Suisse SA' },
    { name: 'Clendy', company: 'EDIFEA' },
    { name: 'Quartier Horizon Lot A', company: 'Complex Bau AG' },
    { name: 'Middes', company: 'EDIFEA' },
    { name: 'Lignon', company: 'Jaccaud Spicher Architectes Associés' },
    { name: "L'Orée", company: 'HRS Real Estate SA' },
    { name: 'Colombière', company: 'Swissroc' },
    { name: 'Panorama', company: 'Puma Construction' },
    { name: 'Le Landeron', company: 'Salchegger Sàrl' },
    { name: 'Colombe', company: 'Swissroc' },
    { name: 'PKE', company: 'Halter SA' },
    { name: 'Crêt des Pierres', company: 'Swissroc' },
    { name: 'Quartier Horizon Lot C', company: 'Porr Suisse AG' },
    { name: 'Borgeaud', company: 'Swissroc' },
    { name: 'Vuarrens', company: 'Salchegger Sàrl' },
    { name: 'Les Coteaux de la Venoge', company: 'Marti Construction SA' },
    { name: 'Galicien', company: 'Pizzera-Poletti SA' },
    { name: 'Coop Caroline', company: 'Losinger Marazzi SA' },
    { name: 'GRP', company: 'HRS Real Estate SA' },
    { name: 'Budé 10', company: 'Swissroc' },
    { name: 'Marais 150', company: 'Swissroc' },
    { name: 'Oiseaux 10', company: 'PP Integra SA' },
    { name: 'Frame Desponds', company: 'ALPENDA' },
    { name: 'Confrérie', company: 'PP Integra SA' },
    { name: 'Roches', company: 'PP Integra SA' },
    { name: 'Quartier Horizon Lot B', company: 'HRS Real Estate SA' },
    { name: 'Jura 11', company: 'Puma Construction' },
    { name: 'Cully 360', company: 'Puma Construction' },
    { name: 'Tissot 16', company: 'Marti Construction SA' },
    { name: 'Audemars Piguet', company: 'ALPENDA' },
    { name: 'Les Jumelles', company: 'ALPENDA' },
    { name: 'Central Malley', company: 'Implenia Suisse SA' },
    { name: 'Immeuble Noville', company: 'NewMind' },
    { name: 'Villeneuve Grand Rue', company: 'Labac Architecture' },
    { name: 'Les Celiers', company: 'EDIFEA' },
    { name: 'KidsCare Morges', company: 'Gottaz' },
    { name: 'Hilton', company: 'ALPENDA' },
    { name: 'Biopole', company: 'Losinger Marazzi SA' },
    { name: 'Just Olivier', company: 'Swissroc' },
    { name: 'Montoie', company: 'Marti Construction SA' },
    { name: 'Boston', company: 'Bernard Nicod' },
    { name: 'Outlet Aubonne', company: 'Own Concept Sàrl' },
    { name: 'Les Lisières', company: 'ALPENDA' },
    { name: 'Mornex', company: 'Atelier Zéro SA' },
    { name: 'Mousse 67', company: 'Swissroc' },
    { name: 'Villa Frech', company: 'Frame Entreprise Générale' },
    { name: 'Lavigny', company: 'Frame Entreprise Générale' },
    { name: 'Alanine', company: 'Bosredon SA' },
    { name: 'Signy Centre', company: 'Halter SA' },
    { name: 'Montpreveyres', company: 'TASQ Sàrl' },
    { name: 'Tannay', company: 'Legato EG' },
    { name: 'Louis Vuitton', company: 'Louis Vuitton' }
];
